### PR TITLE
Add PyTennessee

### PR DESCRIPTION
**Pull request by adriennefriend**
Add PyTennessee to 2018.csv, with thanks! 🎉

### CODE REVIEW

**Comment by hroncok** [comment]
There seem to be a problem with number of columns.

**Comment by adriennefriend** [comment]
@hroncok What does the problem appear to be to you?

**Comment by ewdurbin** [comment]
Two commas before the website URL should do it! That is the column for sponsorship URL/info.

**Comment by adriennefriend** [comment]
Thanks @ewdurbin just noticed that! 😄 Totally didn't notice it the first time around.

**Comment by adriennefriend** [comment]
@hroncok @ewdurbin thanks again! I think I fixed it? Haha.

**Comment by hroncok** [comment]
@adriennefriend thanks for the quick fix.

I found November the 1st as CfP deadline at https://www.pytennessee.org/speaking/cfp/, was it extended?

**Comment by adriennefriend** [comment]
It was, but our website has not been updated yet. Thanks for checking @hroncok

**Comment by adriennefriend** [comment]
I've pinged @epochblue (Conference Chair) to ask what the process would be for getting it updated on our website. @hroncok Thanks again for checking!

**Comment by adriennefriend** [comment]
@hroncok Just so you don't have to go on my word alone :D Here's a [recent announcement about the extension](https://twitter.com/PyTennessee/status/926858345683746817) on Twitter.

**Comment by hroncok** [comment]
There was a typo in the URL (some states names are painful to spell :D), fixed it.

**Comment by hroncok** [comment]
@adriennefriend may I squash it all to one commit?

**Comment by adriennefriend** [comment]
@hroncok Absolutely :D Thank you again for your work here!!

**Comment by hroncok** [comment]
Thanks for the data and enjoy PyTennessee.

**Pull request merged**
