### PR TITLE
adding SciPy 2018

### PR DESCRIPTION
**Pull request by danielskatz**

### CODE REVIEW

**Comment by ewdurbin** [comment]
Hi @danielskatz!

Can you add the `https://scipy2018.scipy.org/ehome/299527/493400//` url for proposals?

**Comment by ewdurbin** [comment]
Other than that I've confirmed all other dates and URLS!

Once we add the URL for proposals, this is ready to go!

**Comment by danielskatz** [comment]
I didn't add that since it there are separate sites for tutorials vs talks, and I wasn't sure which to add, but I will do so now.

**Comment by ewdurbin** [comment]
Thanks for contributing @danielskatz!

**Pull request merged**
