### PR TITLE
:tada: Adds DjangoCon US 2018

### PR DESCRIPTION
**Pull request by jefftriplett**

### CODE REVIEW

**Comment by hroncok** [comment]
The website itself doesn't seem to have the date, so it's hard to check whether it is correct :)

**Comment by treyhunner** [comment]
@hroncok DjangoCon date was just announced last week. [Announcement by DEFNA here](https://www.defna.org/announcements/2017/11/2/djangocon-us-2018-in-san-diego).

**Comment by hroncok** [comment]
Thank you!

**Comment by jefftriplett** [comment]
Np, and thanks for the quick merge. The website is more "in progress" than a work-in-progress" but I added some dates to confirm. More soon. Promise ;)

**Pull request merged**
