### PR TITLE
Add EuroSciPy 2018

### PR DESCRIPTION
**Pull request by pdebuyl**
The CFP and deadlines are not known yet, I can add them when they become available.

### CODE REVIEW

**Comment by hroncok** [comment]
Github says: We can make this file beautiful and searchable if this error is corrected: Missing or stray quote in line 23

**Comment by pdebuyl** [comment]
So?

**Comment by pdebuyl** [comment]
Sorry for the too concise reply. I made the fix of the missing closing quote.

**Comment by pdebuyl** [comment]
Thank you @hroncok (btw, where is the list published?)

**Comment by hroncok** [comment]
You are welcome. (Juts in this repo.)

**Pull request merged**
