### PR TITLE
:pencil: Adds DjangoCon Europe

### PR DESCRIPTION
**Pull request by jefftriplett**

### CODE REVIEW

**Comment by hroncok** [comment]
Should we keep this somehow sorted?

**Comment by hroncok** [comment]
All of the other events seems to be sorted by start date. I'd rather keep it that way.

**Comment by jefftriplett** [comment]
Great point. Updated. I remove the space on US too since that's annoying.

**Comment by hroncok** [comment]
I've merged #9 and cherrypicked the space part in e18034b. Thanks.

**Pull request closed without merging**
