### PR TITLE
Standardize locations

### PR DESCRIPTION
**Pull request by vinayak-mehta**
Hi! :wave: 

I'm using the 2020 csv here: https://github.com/vinayak-mehta/conrad, so standardized the location column to make it easier to parse.

### CODE REVIEW

**Comment by vinayak-mehta** [comment]
Should we validate CSVs in PRs (maybe using a GitHub Action) so that some of the fields are standardized (dates, locations, country codes etc.)? We can use @di's [vladiate](https://github.com/di/vladiate). I can work on it when I find time this week.

**Comment by vinayak-mehta** [comment]
@alanderex Can you please review and merge this? :smiley:

**Comment by alanderex** [comment]
Information like 

> , United States of America",USA

is redundant.

I see there is a need to include the state for some larger states as the US, but the country should not be added next to the city.

**Comment by alanderex** [comment]
Normalized 2020 data in  d150f8e @vinayak-mehta

**Comment by vinayak-mehta** [comment]
Thanks!

**Comment by alanderex** [comment]
Update: in fact now everything should be fine with 91dc4ef

**Comment by vinayak-mehta** [comment]
Thanks again!

**Pull request closed without merging**
